name: Core Unit Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Gradle
      uses: gradle/gradle-build-action@v3

    - name: Run unit tests
      run: gradle :core:test

    - name: Show test summary
      run: |
        echo "### Unit Test Summary" >> $GITHUB_STEP_SUMMARY
        TEST_RESULTS=$(find build/test-results/test -name "*.xml")
        PASSED=$(grep -o 'testsuite.*tests="[^"]*"' $TEST_RESULTS | sed -n 's/.*tests="\([0-9]*\)".*/\1/p' | awk '{s+=$1} END {print s}')
        FAILURES=$(grep -o 'testsuite.*failures="[^"]*"' $TEST_RESULTS | sed -n 's/.*failures="\([0-9]*\)".*/\1/p' | awk '{s+=$1} END {print s}')
        SKIPPED=$(grep -o 'testsuite.*skipped="[^"]*"' $TEST_RESULTS | sed -n 's/.*skipped="\([0-9]*\)".*/\1/p' | awk '{s+=$1} END {print s}')
        echo "- ✅ Passed: $((PASSED - FAILURES - SKIPPED))" >> $GITHUB_STEP_SUMMARY
        echo "- ❌ Failed: $FAILURES" >> $GITHUB_STEP_SUMMARY
        echo "- ⏭️ Skipped: $SKIPPED" >> $GITHUB_STEP_SUMMARY
